### ISSUE TITLE
Server Database hitting max_user_connections

### ISSUE THREAD

**Issue by kennethtran93** [jim-parry/server-botcards#11]
hmmm...

**Comment by kennethtran93** [comment]
we're over-requesting the BCC/status.  if you had added the times, we could possibly implement a check to see if the time has passed before requesting a new status...which would possibly lessen the requests to your db server...

**Comment by jim-parry** [comment]
Agreed. It's not just the ACIT students, but my COMP4711 students too :-/
I've been trying to figure out a way to influence the performance, but have been unsuccessful. Shared hosting, blech.

**Comment by kennethtran93** [comment]
Temporary Solution/workaround:  me setting up a 'backup' server.  See email.

**Comment by jim-parry** [comment]
Hostpapa limits shared hosting to 150 connections, but 15 per user. Their remedy: upgrade to one of their VPS plans. I didn't realiize how light-weight their shared hosting is :(
I will take you up on your offer, thanks - details via email return!
