### ISSUE TITLE
New player handling broken?

### ISSUE THREAD

**Issue by jim-parry** [jim-parry/server-botcards#12]
"At the moment if i use player George or Donald to test buying both are able to purchase cards. However when I attempt to purchase cards with players that I have created on my app I receive the error message "You cannot afford to buy that" this seems to be an error since these players have yet to purchase any cards so they should have a starting amount of 100 peanuts. "

**Comment by kennethtran93** [comment]
Your players table in the database has the `AUTO_INCREMENT` value to **2**.

However, in the Buy Controller, you're trying to get the size of the table which will not correspond to the 'seq' number for that newly created player.

SOLUTION:  Either use `AUTO_INCREMENT` value to **1** on the Players DB Table, or use this on line 63 instead: 
`$one = $this->players->find($team, $player);`

**Comment by jim-parry** [comment]
Thanks, Kenneth!

**Comment by kennethtran93** [comment]
Whoops I lied... Auto_increment was set to 2 to start because you manually inserted a row... but hopefully the fix is working anyway.

Auto_increment intervals is actually a parameter for the entire mysql database, and not per table.
